### ISSUE TITLE
Add ability for auto complete links to be full path

### ISSUE THREAD

**Issue by jacobb** [Feel-ix-343/markdown-oxide#103] opened 2024-05-21 21:25 UTC
Hey there,

Absolutely loving using this, thank you for the work. Hope I can contribute back.

Right now, when auto-completing using markdown style links, the target portion is just the id.

I'd love to be able to include the hard relative path instead, so that converting notes to static site generators is that easy and the pathing is explicit.

Happy to look into helping here if you think it's a worth inclusion.

**Comment by Feel-ix-343** [comment] 2024-05-21 21:51
Hey! I am so happy you are loving using this! Me too hah. 

And this is a very valid request; As I said here #80, I am planning to implement a config option to enable this. 

Origionally, we used path completions, but switched to id completions by default here #2

Also, unfortunately, I think I will need to do this as the related code is not so good - and I am working on a major refactor #90 anyway. There are a couple of other issue such as #95 and maybe #98 that would be much easier for you to help with. I would love to work together!

**Comment by Feel-ix-343** [comment] 2024-05-21 21:51
Duplicate of #80

**Closed** 2024-05-21 21:56 UTC
