### ISSUE TITLE
Failed to start in nvim nightly

### ISSUE THREAD

**Issue by ray-x** [Feel-ix-343/markdown-oxide#11] opened 2024-03-02 11:51 UTC
Thanks for the project. I am trying to move from marksman to oxide project with nvim
But with latest nvim nightly and lspconfig. The lsp server failed to start. 
If I run `lspconfig.markdown_oxide.setup{}`, I have following errors
```
Error executing vim.schedule lua callback: ...software/nvim-nightly/share/nvim/runtime/lua/vim/lsp.lua:1431: RPC[Error] code_name = InvalidParams, 
message = "Invalid params"
stack traceback:
        [C]: in function 'assert'
        ...software/nvim-nightly/share/nvim/runtime/lua/vim/lsp.lua:1431: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
Are there anything must be setup for this lsp?

**Comment by sQVe** [comment] 2024-03-02 13:14
Weird, it works for me on the latest nightly. Do you **only** run `lspconfig.markdown_oxide.setup` ?

**Comment by Feel-ix-343** [comment] 2024-03-02 14:28
Do you have git initialized in the root of your directory? This is the cause of the error right now. This is because the LS requires that `root_dir` be sent, and [the PR into nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/pull/3030) made it so that `root_dir` would only be sent if there git is initialized.  

This is not intended behavior, however. Neovim should send the current working directory as `root_dir`. I think there are some errors in the [PR](https://github.com/neovim/nvim-lspconfig/pull/3030) breaking this.

**Comment by Feel-ix-343** [comment] 2024-03-02 14:28
Also make sure that nvim-lspconfig is fully up to date for you

**Comment by Feel-ix-343** [comment] 2024-03-02 14:33
If you don't want to initialize git, you can work around this also by configuring markdown_oxide like this

```lua
lspconfig.markdown_oxide.setup({
    root_dir = lspconfig.util.root_pattern('.git', vim.fn.getcwd()),
    -- ...your config
})
```


I will try to sort this out

**Comment by ray-x** [comment] 2024-03-02 15:09
I tried to run following in a non-git folder
`:lua require('lspconfig').markdown_oxide.setup({root_dir = require('lspconfig').util.root_pattern('.git', vim.fn.getcwd())})`
But markdown_oxide did not start, I also do not see any error logs, but following works
`:lua require('lspconfig').markdown_oxide.setup({root_dir = require('lspconfig').util.root_pattern('.marksman.toml', '.git', vim.fn.getcwd())})`

**Comment by Feel-ix-343** [comment] 2024-03-04 11:32
Thats quite odd. What context are you calling nvim from? did you `cd {vault}` then call `nvim {path}`

**Comment by ray-x** [comment] 2024-03-04 23:19
It can be `nvim file.md`  or `nvim journal/2024-03-02.md`, Without `.git` the lspinfo is as bellow:

``` 
 Language client log: /Users/rayxu/.local/state/nvim/lsp.log
 Detected filetype:   markdown
 
 1 client(s) attached to this buffer: 
 
 Client: null-ls (id: 2, bufnr: [1])
 	filetypes:       yaml, tex, markdown, python, go, lua, typescript, javascript, fish, json, markdown.mdx, luau, java, ts, sh, js, jsx, toml, html, css, scss, tsx, py
 	autostart:       false
 	root directory:  /Users/rayxu/worknotes
 	cmd:             <function>
 
 Other clients that match the filetype: markdown
 
 Config: markdown_oxide
 	filetypes:         markdown
 	root directory:    /
 	cmd:               /Users/rayxu/bin/markdown-oxide
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 Config: grammarly
 	filetypes:         markdown
 	root directory:    Not found.
 	cmd:               /Users/rayxu/.local/share/pnpm/grammarly-languageserver --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   $/updateDocumentState
 
 Configured servers list: markdown_oxide, emmet_ls, grammarly
 ```

**Comment by Feel-ix-343** [comment] 2024-03-05 00:31
I notice that the root dir is set, but it's set to `/`, which I have never seen before. 

Could you run a `:pwd` in neovim?

**Comment by Feel-ix-343** [comment] 2024-03-05 01:06
I think the issue is that `vim.fn.getcwd()` is not even a function in nvim nightly `NVIM v0.10.0-dev-2507+g3df1211eb`; 

I found a different function: `vim.uv.cwd()`. For some reason this doesn't work with lspconfig.util.root_pattern anymore; I got the following to work:

```lua
root_dir = vim.uv.cwd
```

**Comment by Feel-ix-343** [comment] 2024-03-10 15:41
@ray-x Did this work for you? 

If so, I will add it to the readme and possibly make a PR to nvim-lspconfig and close the issue

**Comment by linsui** [comment] 2024-03-25 13:30
```
root_dir = lspconfig.util.root_pattern('.git', vim.fn.getcwd()),
```

This works for me on 0.9.5. Could you please add a note in readme?

**Comment by Feel-ix-343** [comment] 2024-03-25 14:00
@linsui was the default lspconfig not working for you? I see you are not using nightly

**Comment by linsui** [comment] 2024-03-25 14:13
The default lspconfig doesn't work in a non-git directory. The above config works.

**Comment by Feel-ix-343** [comment] 2024-03-25 18:27
Yea I was running into this issue when making the PR [here](https://github.com/neovim/nvim-lspconfig/pull/3030). The `single_file_support` should set the root dir as CWD automatically but I don't think it is working. Root_dir is not being sent.

I will try to update lspconfig to fix this and add a note to the readme.

**Comment by ray-x** [comment] 2024-03-25 22:32
Seems it requires a file/folder e.g.`.markdownlint.json` or `.git` to work properly. Am I missing anything?

**Comment by Feel-ix-343** [comment] 2024-03-25 22:38
Thats shouldnt work if you are using nvim 10 as vim.fn.cws is removed. In your case vim.uv.cwd should work in place of vim.fn.cwd

You also may have to wrap the vim.uv.cwd in a function if I remember correctly

Let me know if this solves it @ray-x and ill append to the readme

**Comment by ray-x** [comment] 2024-03-26 23:28
Following setup works for me:

```lua
    root_dir = function()
      return lspconfig.util.root_pattern('.git', '.markdownlint.json')(vim.uv.cwd())
    end,

```

**Comment by linsui** [comment] 2024-04-16 13:42
I just found that

```lua
root_dir = lspconfig.util.root_pattern('.git', vim.fn.getcwd()),
```

doesn't really work. This works instead:

```lua
root_dir = function(fname, _)
  return require("lspconfig").util.root_pattern('.git')(fname) or vim.fn.getcwd()
end,
```

**Comment by Feel-ix-343** [comment] 2024-04-16 14:08
Hey nixos friend! Thanks!

Is this on nvim nightly?

**Comment by linsui** [comment] 2024-04-16 14:11
No, I'm still on v0.9.5.

**Comment by Feel-ix-343** [comment] 2024-04-16 14:13
Ok. I'll do some more research on this because there have been many issues reported about it. Then ill make the lspconfig pull request.


Another simple solution could be for the language server to treat the dir of the first opened file as the root directory if one cannot be found otherwise.

**Comment by Feel-ix-343** [comment] 2024-04-23 11:59
This should be merged into nvim-lspconfig now; I used @linsui 's pattern but changed to use vim.uv.cwd() as vim.fn.getcwd() will be depreciated in nvim 10

**Closed by Feel-ix-343** 2024-04-23 11:59 UTC
